FROM chuanwen/cowsay:latest
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "#VQV Trybe" ]

# P/ BUILDAR, ESTANDO NA PASTA, UTILIZE: docker image build ./ -t cowsay
# P/ RODAR, ESTANDO NA PASTA, UTILIZE: 
# - docker container run cowsay "<MENSAGEM>"
# - docker container run cowsay -f dragon-and-cow "#VQV TRYBE"